import {
  Activity,
  Backpack,
  Banknote,
  BriefcaseMedical,
  Calculator,
  CarTaxiFront,
  CreditCard,
  Drill,
  Dumbbell,
  FireExtinguisher,
  Fuel,
  Gift,
  HandCoins,
  HandPlatter,
  Handshake,
  Hospital,
  House,
  HousePlus,
  Landmark,
  MonitorPlay,
  Pill,
  Pizza,
  PlaneTakeoff,
  ReceiptText,
  Shirt,
  ShoppingCart,
  Shuffle,
  Sparkles,
  Stethoscope,
  TabletSmartphone,
  Tag,
  TentTree,
  TicketMinus,
  TramFront,
  Truck,
  Tv,
  User,
  Utensils,
  Wifi,
  Zap,
} from "lucide-react";

export const mappings = {
  "food:restaurant": Utensils,
  "food:groceries": ShoppingCart,
  "food:online": Pizza,
  "food:other": HandPlatter,
  "utilities:gas": FireExtinguisher,
  "utilities:internet": Wifi,
  "utilities:electricity": Zap,
  "utilities:mobile": TabletSmartphone,
  "utilities:dth": Tv,
  "utilities:other": MonitorPlay,
  "transportation:fuel": Fuel,
  "transportation:service-repairs": TicketMinus,
  "transportation:motor-insurance": ReceiptText,
  "transportation:flight": PlaneTakeoff,
  "transportation:train": TramFront,
  "transportation:cab": CarTaxiFront,
  "transportation:other": Truck,
  "household:maid": User,
  "household:maintenance": Drill,
  "household:property-tax": Calculator,
  "household:goods": House,
  "household:rent": Banknote,
  "household:other": HousePlus,
  "health:medicines": Pill,
  "health:hospitalization": Hospital,
  "health:doctor-visit": Stethoscope,
  "health:insurance": BriefcaseMedical,
  "health:other": Activity,
  "personal:shopping": Shirt,
  "personal:subscription": Handshake,
  "personal:fitness": Dumbbell,
  "personal:vacation": TentTree,
  "personal:beauty": Sparkles,
  "personal:gift-donation": Gift,
  "personal:other": Backpack,
  "income:salary": HandCoins,
  "income:cashback": HandCoins,
  "income:credit": HandCoins,
  "income:other": HandCoins,
  "transfer:acct-to-acct": Shuffle,
  "transfer:cc-payment": CreditCard,
  "transfer:atm-withdrawal": Landmark,
  "transfer:wallet-recharge": Shuffle,
  "transfer:other": Shuffle,
  "miscellaneous:miscellaneous": Tag,
};

type Props = {
  name: keyof typeof mappings;
};

export default function Icon({ name }: Props) {
  const Icon = mappings[name] ?? Tag;
  return <Icon className="size-6" />;
}
